services:
  app:
    build: .
    container_name: wideresearcher-application
    restart: always
    ports:
      - "${DOCKER_APP_PORT}:8000"
    networks:
      - wideresearcher-network
    volumes:
      - ./app:/workdir/app
      - ./.env:/workdir/.env
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7.2
    container_name: wideresearcher-redis
    restart: always
    ports:
      - "${DOCKER_REDIS_PORT}:6379"
    networks:
      - wideresearcher-network
    command: ["redis-server", "--requirepass", "${REDIS__PASSWORD}"]

  postgres:
    image: postgres:18
    container_name: wideresearcher-postgres
    restart: always
    environment:
      POSTGRES_DB: ${SQL__DATABASE}
      POSTGRES_USER: ${SQL__USER}
      POSTGRES_PASSWORD: ${SQL__PASSWORD}
    ports:
      - "${DOCKER_SQL_PORT}:5432"
    volumes:
      - wideresearcher-data:/var/lib/postgresql/data
    networks:
      - wideresearcher-network

networks:
  wideresearcher-network:

volumes:
  wideresearcher-data: